<template>
  <div
    class="
      2xl:px-10
      xl:px-10
      lg:px-10
      px-0
      mt-10
      2xl:ml-56
      xl:ml-56
      lg:ml-0
      flex
      md:mr-64
      4xl:mr-44
      5xl:mr-32
      sm:mr-52
      justify-between
      xl:flex
      lg:block
      md:block
      sm:block
      4xl:block
      5xl:block
      xs:block
    "
  >
    <div>
      <div
        class="
          direction
          flex
          2xl:flex
          xl:flex
          lg:block
          md:block
          4xl:block
          5xl:block
          xs:block
        "
      >
        <img
          class="
            w-16
            4xl:mr-16
            2xl:ml-0
            sm:mr-12
            md:mr-12
            xl:ml-0
            lg:ml-0
            ml-16
            h-16
            5xl:mr-12
          "
          src="storekerovat.png"
          alt=""
        />
        <div class="mt-2">
          <div class="mr-1">ارسال فوری در تهران وحومه</div>
          <div class="mr-2">تحویل کمتراز 20دقیقه</div>
        </div>
      </div>
    </div>
    <div>
      <div
        class="
          flex
          2xl:flex
          xl:flex
          lg:block
          md:block
          4xl:block
          5xl:block
          direction
          xs:block
        "
      >
        <img
          class="
            w-16
            4xl:mr-16
            h-16
            sm:mr-12
            md:mr-12
            2xl:ml-0
            xl:ml-0
            lg:ml-0
            5xl:mr-12
            ml-16
          "
          src="roban.png"
          alt=""
        />
        <div>
          <div class="mr-3">برگزاری بهترین دوره های آموزشی</div>
          <div class="mr-3">بیشترین تعداد هنرجو درایران</div>
        </div>
      </div>
    </div>
    <div>
      <div
        class="
          flex
          2xl:flex
          xl:flex
          lg:block
          md:block
          4xl:block
          5xl:block
          xs:block
          direction
        "
      >
        <img
          class="
            w-16
            4xl:mr-16
            h-16
            md:mr-12
            sm:mr-12
            2xl:ml-0
            xl:ml-0
            5xl:mr-12
            lg:ml-0
            ml-16
          "
          src="home.png"
          alt=""
        />
        <div class="mt-2">
          <div class="mr-3">شعب متعدددرسراسرایران</div>
          <div class="mr-3">بیش از20شعبه فعال</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>